# This is a basic workflow to help you get started with Actions

name: Validate YAML

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Hmerac/kubeval-action@1.2
      with:
        command: |
          echo "Running kubeval"
          kubeval -d manifests --strict
