on: [push, pull_request]
name: ValidateYAML
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: test
      uses: instrumenta/kubeval-action@master
      with:
        files: "*.yaml"
        token: ${{ secrets.GITHUB_TOKEN }}
