# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Kubernetes yaml validation by conftest
      uses: makocchi-git/actions-k8s-manifests-validate-conftest@v1.1.0
      with:
        # File or directory to validate
        file: # optional, default is .
        # Output format for conftest results - valid options are: [stdout json tap table]
        output: # optional, default is stdout
        # Path to the Rego policy files directory
        policy: # optional, default is /policy
        # Enable more verbose trace output for rego queries
        trace: # optional
        # A list of urls can be provided to the update flag, which will download before the tests run
        update: # optional, default is 
        # Send comment to pull requests
        comment: # optional, default is true
        # Github token for api. This is required if comment is true
        token: # optional, default is 
